### ISSUE TITLE
Do you have python code of RaBitQ?

### ISSUE THREAD

**Issue by Godzilla0517** [kemingy/rabitq#1]
It's really awesome to reproduce RaBitQ in Rust, I'd like to ask you if you have the python code for RaBitQ, the C++ code for RaBitQ is too complex and I've made many attempts to reproduce it in python, I'd appreciate if you can provide the python code.I would appreciate it if you could provide me with the python code!Thank you for your help!Thank you!

**Comment by kemingy** [comment]
I don't have a Python version. I agree the code is complex and it's hard to debug.
